services:
  - type: worker
    name: qr-code-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: python Qrcode.py